<style>
    .user {border: 1px solid black; width: 300px; min-height: 50px; max-height: 250px; margin-top: 10px; position: relative}
    .add_user {margin-top: 50px}
</style>
<script src="/js/jquery-3.7.1.min.js"></script>
<script src="/js/functions.js"></script>
Список пользователей:<br>
<?php if($users = $this->data['users']): ?>
    <?php foreach($users as $user): ?>
        <div class="user" id="user_block_<?=$user->getId();?>">
        id пользователя: <?=$user->getId();?><br>
        Имя: <input type="text" id="user_name_<?=$user->getId();?>" value="<?=htmlspecialchars($user->getName());?>"><br>
        Email: <input type="text" id="user_email_<?=$user->getId();?>" value="<?=htmlspecialchars($user->email);?>"><br>
        Пароль: <input type="text" id="user_password_<?=$user->getId();?>"><br>
        <input type="button" onclick="saveUser(<?=$user->getId();?>);" value="Сохранить">
        <input type="button" onclick="deleteUser(<?=$user->getId();?>);" value="Удалить">
            <div id="response_<?=$user->getId();?>">

            </div>
        </div>
    <?php endforeach; ?>
<?php endif; ?>

<br><br><div class="add_user">Добавить пользователя:</div><br>
    Имя: <input type="text" id="user_name"><br>
    Email: <input type="text" id="user_email"><br>
    Пароль: <input type="text" id="user_password"><br>
    <input type="button" onclick="addUser();" value="Добавить">
    <div id="response">

    </div>
